package handling;

import constants.GameConstants;
import static handling.RecvPacketOpcode.values;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Properties;

public enum RecvPacketOpcode
        implements WritableIntValueHolder {
    PONG(false),
    CLIENT_HELLO(false),
    LOGIN_REDIRECTOR(false),
    LOGIN_PASSWORD(false),
    CLIENT_START(false),
    LOGIN_PASSWORD2(false),
    CLIENT_AUTH(false),
    SEND_ENCRYPTED(false),
    CLIENT_ERROR(false),
    RSA_KEY(false),
    STRANGE_DATA,
    CRASH_INFO(false),
    CLIENT_FAILED(false),
    PLAYER_LOGGEDIN(false),
    ENTER_FARM(false),
    GUEST_LOGIN(true),
    SERVERSTATUS_REQUEST(false),
    TOS(true),
    VIEW_SERVERLIST(false),
    SERVERLIST_REQUEST(false),
    REDISPLAY_SERVERLIST(false),
    CHAR_SELECT_NO_PIC(false),
    CHECK_CHAR_NAME(true),
    DELETE_CHAR(true),
    AUTH_REQUEST(false),
    CHAR_SELECT(true),
    VIEW_REGISTER_PIC(true),
    CHANGE_PIC_REQUEST(true),
    VIEW_SELECT_PIC(true),
    PART_TIME_JOB(true),
    CHARACTER_CARD(true),
    ENABLE_LV50_CHAR(true),
    CREATE_LV50_CHAR(true),
    ENABLE_SPECIAL_CREATION(true),
    CREATE_SPECIAL_CHAR(true),
    CHARLIST_REQUEST(false),
    CREATE_CHAR(false),
    CREATE_ULTIMATE,
    AUTH_SECOND_PASSWORD(true),
    WRONG_PASSWORD(false),
    /*
     * Channel Opcodes.
     * Used for in-game packets.
     */
    CHANGE_MAP(true),
    CHANGE_CHANNEL(true),
    ENTER_CASH_SHOP(true),
    ENTER_AZWAN(true),
    ENTER_AZWAN_EVENT(true),
    LEAVE_AZWAN(true),
    ENTER_PVP(true),
    ENTER_PVP_PARTY(true),
    LEAVE_PVP(true),
    MOVE_PLAYER(true),
    CANCEL_CHAIR(true),
    USE_CHAIR(true),
    CLOSE_RANGE_ATTACK(true),
    RANGED_ATTACK(true),
    MAGIC_ATTACK(true),
    PASSIVE_ENERGY(true),
    TAKE_DAMAGE(true),
    PVP_ATTACK(true),
    GENERAL_CHAT(true),
    CLOSE_CHALKBOARD(true),
    FACE_EXPRESSION(true),
    FACE_ANDROID(true),
    USE_ITEMEFFECT(true),
    WHEEL_OF_FORTUNE(true),
    USE_TITLE(true),
    ANGELIC_CHANGE(true),
    CHANGE_CODEX_SET(true),
    CODEX_UNK(true),
    MONSTER_BOOK_DROPS(true),
    NPC_TALK(true),
    NPC_TALK_MORE(true),
    NPC_SHOP(true),
    STORAGE(true),
    USE_HIRED_MERCHANT(true),
    MERCH_ITEM_STORE(true),
    PACKAGE_OPERATION(true),
    MECH_CANCEL(true),
    HOLLY(true),
    OWL(true),
    OWL_WARP(true),
    ITEM_SORT(true),
    ITEM_GATHER(true),
    ITEM_MOVE(true),
    MOVE_BAG(true),
    SWITCH_BAG(true),
    USE_ITEM(true),
    CANCEL_ITEM_EFFECT(true),
    USE_SUMMON_BAG(true),
    PET_FOOD(true),
    USE_MOUNT_FOOD(true),
    USE_SCRIPTED_NPC_ITEM(true),
    USE_RECIPE(true),
    USE_NEBULITE(true),
    USE_ALIEN_SOCKET(true),
    USE_ALIEN_SOCKET_RESPONSE(true),
    USE_NEBULITE_FUSION(true),
    USE_CASH_ITEM(true),
    USE_CATCH_ITEM(true),
    USE_SKILL_BOOK(true),
    USE_EXP_POTION(true),
    TOT_GUIDE(true),
    USE_OWL_MINERVA(true),
    USE_TELE_ROCK(true),
    USE_RETURN_SCROLL(true),
    USE_UPGRADE_SCROLL(true),
    USE_FLAG_SCROLL(true),
    USE_EQUIP_SCROLL(true),
    USE_POTENTIAL_SCROLL(true),
    USE_BONUS_POTENTIAL(true),
    USE_ABYSS_SCROLL(true),
    USE_CARVED_SEAL(true),
    USE_BAG(true),
    USE_CRAFTED_CUBE(true),
    USE_MAGNIFY_GLASS(true),
    DISTRIBUTE_AP(true),
    AUTO_ASSIGN_AP(true),
    HEAL_OVER_TIME(true),
    LINK_SKILL(true),
        IDK_1(true),
    IDK_2(true),
    IDK_3(true),
    IDK_4(true),
    DISTRIBUTE_SP(true),
    SPECIAL_MOVE(true),
    CANCEL_BUFF(true),
    SKILL_EFFECT(true),
    MESO_DROP(true),
    GIVE_FAME(true),
    CHAR_INFO_REQUEST(true),
    SPAWN_PET(true),
    GET_BOOK_INFO(true),
    USE_FAMILIAR(true),
    SPAWN_FAMILIAR(true),
    RENAME_FAMILIAR(true),
    PET_BUFF(true),
    CANCEL_DEBUFF(true),
    CHANGE_MAP_SPECIAL(true),
    USE_INNER_PORTAL(true),
    TROCK_ADD_MAP(true),
    LIE_DETECTOR(true),
    LIE_DETECTOR_SKILL(true),
    LIE_DETECTOR_RESPONSE(true),
    REPORT(true),
    QUEST_ACTION(true),
    REISSUE_MEDAL(true),
//    BUFF_RESPONSE,
    SKILL_MACRO(true),
    REWARD_ITEM(true),
    ITEM_MAKER(true),
    REPAIR_ALL(true),
    REPAIR(true),
    SOLOMON(true),
    GACH_EXP(true),
    FOLLOW_REQUEST(true),
    PQ_REWARD(true),
    FOLLOW_REPLY(true),
    AUTO_FOLLOW_REPLY(true),
    USE_TREASURE_CHEST(true),
    PROFESSION_INFO(true),
    USE_POT(true),
    CLEAR_POT(true),
    FEED_POT(true),
    CURE_POT(true),
    REWARD_POT(true),
    AZWAN_REVIVE(true),
    ZERO_TAG(true),
    USE_COSMETIC(true),
    INNER_CIRCULATOR(true),
    PVP_RESPAWN(true),
    GAIN_FORCE(true),
    ADMIN_CHAT(true),
    PARTYCHAT(true),
    COMMAND(true),
    SPOUSE_CHAT(true),
    MESSENGER(true),
    PLAYER_INTERACTION(true),
    PARTY_OPERATION(true),
    DENY_PARTY_REQUEST(true),
    ALLOW_PARTY_INVITE(true),
    EXPEDITION_OPERATION(true),
    EXPEDITION_LISTING(true),
    GUILD_OPERATION(true),
    DENY_GUILD_REQUEST(true),
    ADMIN_COMMAND(true),
    ADMIN_LOG(true),
    BUDDYLIST_MODIFY(true),
    NOTE_ACTION(true),
    USE_DOOR(true),
    USE_MECH_DOOR(true),
    CHANGE_KEYMAP(true),
    RPS_GAME(true),
    RING_ACTION(true),
    WEDDING_ACTION(true),
    ALLIANCE_OPERATION(true),
    DENY_ALLIANCE_REQUEST(true),
    REQUEST_FAMILY(true),
    OPEN_FAMILY(true),
    FAMILY_OPERATION(true),
    DELETE_JUNIOR(true),
    DELETE_SENIOR(true),
    ACCEPT_FAMILY(true),
    USE_FAMILY(true),
    FAMILY_PRECEPT(true),
    FAMILY_SUMMON(true),
    BBS_OPERATION(true),
    SOLOMON_EXP(true),
    NEW_YEAR_CARD(true),
    XMAS_SURPRISE(true),
    TWIN_DRAGON_EGG(true),
    ARAN_COMBO(true),
    TRANSFORM_PLAYER(true),
    CYGNUS_SUMMON(true),
    CRAFT_DONE(true),
    CRAFT_EFFECT(true),
    CRAFT_MAKE(true),
    CHANGE_ROOM_CHANNEL(true),
    EVENT_CARD(true),
    CHOOSE_SKILL(true),
    SKILL_SWIPE(true),
    VIEW_SKILLS(true),
    CANCEL_OUT_SWIPE(true),
    YOUR_INFORMATION(true),
    FIND_FRIEND(true),
    PINKBEAN_CHOCO_OPEN(true),
    PINKBEAN_CHOCO_SUMMON(true),
    CASSANDRAS_COLLECTION(true),
    BUY_SILENT_CRUSADE(true),
    BUDDY_ADD(true),
    MOVE_PET(true),
    PET_CHAT(true),
    PET_COMMAND(true),
    PET_LOOT(true),
    PET_AUTO_POT(true),
    PET_IGNORE(true),
    MOVE_HAKU(true),
    CHANGE_HAKU(true),
    //HAKU_1D8,
    //HAKU_1D9,
    MOVE_SUMMON(true),
    SUMMON_ATTACK(true),
    DAMAGE_SUMMON(true),
    SUB_SUMMON(true),
    REMOVE_SUMMON(true),
    PVP_SUMMON(true),
    MOVE_DRAGON(true),
    USE_ITEM_QUEST(true),
    MOVE_ANDROID(true),
    UPDATE_QUEST(true),
    QUEST_ITEM(true),
    MOVE_FAMILIAR(true),
    TOUCH_FAMILIAR(true),
    ATTACK_FAMILIAR(true),
    REVEAL_FAMILIAR(true),
    QUICK_SLOT(true),
    PAM_SONG(true),
    MOVE_LIFE(true),
    AUTO_AGGRO(true),
    FRIENDLY_DAMAGE(true),
    MONSTER_BOMB(true),
    HYPNOTIZE_DMG(true),
    MOB_BOMB(true),
    MOB_NODE(true),
    DISPLAY_NODE(true),
    MONSTER_CARNIVAL(true),
    NPC_ACTION(true),
    ITEM_PICKUP(true),
    DAMAGE_REACTOR(true),
    TOUCH_REACTOR(true),
    CLICK_REACTOR(true),
    MAKE_EXTRACTOR(true),
    RECEIVE_GIFT_EFFECT(true),
    UPDATE_ENV(true),
    SNOWBALL(true),
    LEFT_KNOCK_BACK(true),
    CANDY_RANKING(true),
    START_EVOLUTION(true),
    COCONUT(true),
    SHIP_OBJECT(true),
    PARTY_SEARCH_START(true),
    PARTY_SEARCH_STOP(true),
    START_HARVEST(true),
    STOP_HARVEST(true),
    QUICK_MOVE(true),
    CS_UPDATE(true),
    BUY_CS_ITEM(true),
    COUPON_CODE(true),
    CASH_CATEGORY(true),
    PLACE_FARM_OBJECT(true),
    FARM_SHOP_BUY(true),
    FARM_COMPLETE_QUEST(true),
    FARM_NAME(true),
    HARVEST_FARM_BUILDING(true),
    USE_FARM_ITEM(true),
    RENAME_MONSTER(true),
    NURTURE_MONSTER(true),
    CS_SURPRISE(true),
    EXIT_FARM(true),
    FARM_QUEST_CHECK(true),
    FARM_FIRST_ENTRY(true),
    GOLDEN_HAMMER(true),
    VICIOUS_HAMMER(true),
    PYRAMID_BUY_ITEM(true),
    CLASS_COMPETITION(true),
    MAGIC_WHEEL(true),
    REWARD(true),
    BLACK_FRIDAY(true),
    UPDATE_RED_LEAF(true),
    //Not Placed:
    SPECIAL_STAT(true),
    UPDATE_HYPER(true),
    RESET_HYPER(true),
    DRESSUP_TIME(true),
    DF_COMBO(true),
    BUTTON_PRESSED(true),
    OS_INFORMATION(true),
    LUCKY_LOGOUT(true),
    MESSENGER_RANKING(true);
    private short code = -2;
    
    private boolean CheckState;

    @Override
    public void setValue(short code) {
        this.code = code;
    }

    @Override
    public final short getValue() {
        return (short) code;
    }

    private RecvPacketOpcode() {
        this.CheckState = true;
    }

    private RecvPacketOpcode(boolean CheckState) {
        this.CheckState = CheckState;
    }

    public final boolean NeedsChecking() {
        return this.CheckState;
    }

    public static Properties getDefaultProperties() throws FileNotFoundException, IOException {
        Properties props = new Properties();
        FileInputStream fileInputStream = new FileInputStream(GameConstants.GMS ? "recvopsGMS.properties" : "recvops.properties");
        props.load(fileInputStream);
        fileInputStream.close();
        return props;
    }

    public static void reloadValues() {
        try {
            ExternalCodeTableGetter.populateValues(getDefaultProperties(), values());
        } catch (IOException e) {
            throw new RuntimeException("Failed to load recvops", e);
        }
    }

    static {
        reloadValues();
    }
}